### ISSUE TITLE
how to make dataset

### ISSUE THREAD

**Issue by Johnson-yue** [hologerry/AGIS-Net#2]
Hi, thank you for sharing your code , I want to know how did you make dataset .

would you like release code about make dataset ??  I have ttf files and I want to make more train dataset and test your Network

**Comment by hologerry** [comment]
You can refer to the `xxx_dataset.py`'s [`__getitem__`](https://github.com/hologerry/AGIS-Net/blob/f271a6848de276da6b0ced82ff70260320eb77b8/data/few_fusion_dataset.py#L31) to see how the data is arranged, please download the dataset for more details.

With `.ttf` font file(s), you can use the following code to render glyph images:
[font2image](https://github.com/hologerry/font2image)

**Comment by Johnson-yue** [comment]
thank you， I will try it
