### ISSUE TITLE
test_base_gray_texture have error configure

### ISSUE THREAD

**Issue by Johnson-yue** [hologerry/AGIS-Net#5]
Hi, I pretrain with base_gray_color dataset, and fine-tune with base_gray_texture, and then I test by run  as your Readme.md said:

> bash ./scripts/test_base_gray_texture.sh GPU_ID DATA_ID

Error:
![Screenshot from 2019-10-18 13-50-10](https://user-images.githubusercontent.com/10268274/67069017-4ffb8d00-f1ae-11e9-860d-3fb63ebc54bc.png)

Then I check your bash file  there are something wrong in [code](https://github.com/hologerry/AGIS-Net/blob/d0be8d063e920c5a2c5d0972f685d7b8f7de0fbd/scripts/test_base_gray_texture.sh#L21)

**Comment by Johnson-yue** [comment]
OK, I change the --few_size default value is 6 and it work but the result is :
![Screenshot from 2019-10-18 14-01-20](https://user-images.githubusercontent.com/10268274/67069616-4a06ab80-f1b0-11e9-80bf-bfdbf4bb08b5.png)

I train with **base_gray_color** dataset and fine-tune with **base_gray_text**:
the train command line is the same ,so I do not necessary write it ,and my fine-tune command is : 

> $bash ./scripts/train.sh base_gray_texture 0 20 6

and **Test**  is :  

> $ bash ./scripts/test_base_gray_texture.sh 0 20

**Comment by hologerry** [comment]
For `xxx_xxx_texture`(fine-tune) dataset, please use the `train_xx_xx_texture.sh` as the `README.md` said, it will produce the test results.

**Comment by Johnson-yue** [comment]
Yes, First I use

> $bash ./scripts/train.sh base_gray_texture 0 20 6
for **Fine-tune** ,and then I run

> bash ./scripts/test_base_gray_texture.sh 0 20
for **Test** and generate other char

Which step wrong ?

**Comment by hologerry** [comment]
Let me explain these two script:
First one:
```bash
$ bash ./scripts/train.sh base_gray_texture 0 20 6
```
It fine-tune the dataset, and for every 50 epoch, it will test on all glyphs synthesis images(in `validation_logs/`). You can use these images as the 'results'.

Second one.
It just load the trained models and run test once. You can use these images as the 'results'.
