### ISSUE TITLE
LSGAN loss is better for Standard GAN loss?

### ISSUE THREAD

**Issue by Johnson-yue** [hologerry/AGIS-Net#6]
Hi, in paper and #4  you said that your experiments only use standard one , I think it is "DCGAN loss"  but in your code  you use ***LSGAN loss** replaced , why ??

Is better performance LSGAN than DCGAN ?? I think you test DCGAN loss  finished?

**Comment by hologerry** [comment]
Actually, we just use the GAN loss from the BicycleGAN/CycleGAN(you can find the link in readme), we did not modify this part, we refer this popular used one as 'standard'.
