### ISSUE TITLE
why are you using retain_graph=True in G_loss backward

### ISSUE THREAD

**Issue by Johnson-yue** [hologerry/AGIS-Net#8]
https://github.com/hologerry/AGIS-Net/blob/8a744ff6c4f329a95daab0aa4f728d8be3858da4/models/agisnet_model.py#L222

**Comment by hologerry** [comment]
Twice?

**Comment by Johnson-yue** [comment]
yes, like this:

![Screenshot from 2019-10-24 17-15-44](https://user-images.githubusercontent.com/10268274/67471429-fdc0dd00-f681-11e9-8171-dd83d92ba514.png)

you backward loss_1 for some gradient , and you want to backward loss_2 for all gradient ,so you use

>  loss1.backward(retain_graph=True)
